### ISSUE TITLE
Report a vulnerability in this repository

### ISSUE THREAD

**Issue by ClearloveX7** [Trivernis/bromine#43]
Hello, we have found a vulnerability in this repository, which may present serious security risks. However, we have been unable to locate a contact email to report the details of this vulnerability. We would like to know if you can provide an email address to confidentially discuss this matter and avoid public disclosure.

**Comment by riking** [comment]
This may be the ASAN stack-use-after-return in version 0.21.0: https://asan.saethlin.dev/ub?crate=bromine&version=0.21.0

@Trivernis please check whether you've already fixed this!

**Comment by Trivernis** [comment]
This doesn't seem to occur in the latest version after updating dependencies
